---
deployment:
  tasks:
    - DEPLOYPATH="/home/$USER/public_html"
    - TEMPDIR="/home/$USER/tmp/public_html"
    - REPOPATH="/home/${USER}/repositories"
    - rm -r $TEMPDIR; mkdir $TEMPDIR
    - cp -r ${DEPLOYPATH}/.well-known ${TEMPDIR}/.well-known
    - cp -r ${DEPLOYPATH}/cgi-bin ${TEMPDIR}/cgi-bin
    - cp -r ${DEPLOYPATH}/index.phtml ${TEMPDIR}/index.phtml
    - cp -r ${REPOPATH}/sajt-git/. ${DEPLOYPATH}/*
